_target_: src.training.samplers.ddpm.DDPMSampler

name: ddpm

num_steps: 100
cfg_rate: ${diffuser.guidance_weight}

scheduler:
  _target_: src.training.noise_schedulers.cosine.CosineScheduler
  clip_min: 1e-9